### ISSUE TITLE
Room name change automatically after entering

### ISSUE THREAD

**Issue by DanielLortie** [MeetHub-io/meethub-support#5]
**Describe the bug**
The room name is changed once you have entered it. The name seems to be a random name.
the most frequent name is "Pluck" if that helps

**To Reproduce**
1. Create 2 rooms and Pin them
2. Enter one of the rooms
3. Then look back at the hub, the room name should have changed. It does every time for me

**Expected behavior**
The room name should not change unless the creator edits it.

**Screenshots**
![image](https://user-images.githubusercontent.com/77454032/104620408-f7d76300-565c-11eb-9119-26837d0bc615.png)
![image](https://user-images.githubusercontent.com/77454032/104620455-03c32500-565d-11eb-973c-bec178903285.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 87.0.4280.141 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 - Browser: 
 - Version
**Additional context**

**Comment by maxmil** [comment]
I can confirm that this is a bug. Thanks for reporting it @DanielLortie.

MeetHub uses randomly generated names (Pluck is an example) for meetings that that the user hasn't given a name in MeetHub (by editing the room). However if the user starts a new Meet and supplies a name it picks that up. This is the case with collaboration_se in the above image.

The bug is that it is not treating this the same way as a name defined in meethub and it is being replaced by a randomly generated name again.

This should be an easy fix.

**Comment by maxmil** [comment]
That should now be fixed @DanielLortie. Thanks again for a very well explained bug report.
